language: cpp

branches:
  only:
    - travis

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check

script: ./autogen.sh && ./configure && make && make check

compiler:
  - clang
  - gcc

notifications:
  email:
    - torquedev@supercluster.org
